version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - err113
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wsl_v5
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 20
    cyclop:
      max-complexity: 20
    gosec:
      severity: medium
      confidence: medium
    lll:
      line-length: 120
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
        - name: var-naming
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
          - funlen
          - gocyclo
        path: _test\.go
      - linters:
          - lll
        source: "^//go:generate "
      - linters:
          - gosec
        text: "G104:"
      - path: (.+)\.go$
        text: exported .* should have comment or be unexported
      - path: (.+)\.go$
        text: package comment should be of the form
    paths:
      - third_party$
      - builtin$
      - examples$
      - '.*_test\.go$'
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - streamshoter
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$